// <auto-generated />
namespace Project_Builder_Development.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adding_userId_field_in_register1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_userId_field_in_register1));
        
        string IMigrationMetadata.Id
        {
            get { return "201905261838055_adding_userId_field_in_register1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
