// <auto-generated />
namespace Project_Builder_Development.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedRequestClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedRequestClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201907181922049_added Request Class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
